### ISSUE TITLE
Weather Card

### ISSUE THREAD

**Issue by greg520820** [briis/visualcrossing#51]
Any advice on a weather card for this integration?  I like the information and display of the custom weather card, but it will not display the forecast information (daily or hourly) from your Visual Crossing Weather integration. It does display the detailed information.  

I was able to get the forecast information to display in the custom weather card, but needed to create a forecast sensor from the Visual Crossing weather entity and it using the forecast attribute, which I believe is being deprecated next month. Also this method throws many errors because the forecast sensor I created is not recognized as being in the Weather domain. 

Any help or suggestions would be appreciated.

**Comment by jeffjensen** [comment]
I've used and dumped a few.  My current fav is "Weather Chart Card", works
great (supports the new weather entity), good info and design (I have it
added twice - once for Hourly and once for Daily), and is a very responsive
developer worthy of "multiple coffees"!

Search for it in HACS Frontend.
https://github.com/mlamberts78/weather-chart-card

**Comment by greg520820** [comment]
Thanks, I'll give it a try.
